### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Xaikii** [thebrightspark/ExtraSkills#1]
https://pastebin.com/g54W9iMP

**Comment by thebrightspark** [comment]
I'm not around to fix this until probably Monday, but until then can you please at least provide as much info as possible?

Did this happen on the client or server? What's the contents of your JSON file? What icon images do you have for your skills? What version of Reskillable do you have?

**Comment by thebrightspark** [comment]
Fixed in https://github.com/thebrightspark/ExtraSkills/commit/5f86979685f8a8b8e82d2de3750b297755f5c533
