### ISSUE TITLE
Skill name display and icon

### ISSUE THREAD

**Issue by Javinyx** [thebrightspark/ExtraSkills#2]
Hello, today I tried adding my first skill and noticed a few things:

1. I tried using this config 
`[
  {
    "name": "example",
    "localName": "Example",
    "background": "stone"
  }
  {
    "name": "archery",
    "localName": "Archery",
    "background": "stone"
  }
]`
But the archery skill did not show up at all.

2. So then I tried 
`[
  {
    "name": "archery",
    "localName": "Archery",
    "background": "stone"
  }
]`
And it worked fine.

3. Although this is what it shows: https://i.imgur.com/zXzgKZ0.png
4. I don't understand how to add the icon - I uploaded a 64x64 png image but where do I put it and where do I call it in the config?

Nonetheless love this addon!

**Comment by thebrightspark** [comment]
I believe the issue with the first example you provided is that you're missing a comma between the two skills. Remember you still need to abide by JSON syntax 😃 You probably would have found a JSON parsing error in your logs.

The icon should go in the mod's config directory (same place as the JSON file). I did state this on the mod page description, but maybe it wasn't clear enough? If not, I'm willing to take advice from an outside perspective on a better description.

It's worth pointing out that I've been made aware of some issue, so I will try get everything fixed for the next release. Give me a day or two and we'll see how it goes 😄

**Comment by thebrightspark** [comment]
Seems like a false alarm on the other issues 😃 

Just tested in a real environment again and I can get a test skill working fine.
Where do you have the JSON file? It should be located in the extraskills config directory that's generated.

**Comment by Javinyx** [comment]
Oh my god, sorry I didn't realise I needed a comma, not used to json, my fault..
The json file is in config/extraskills/ and the icon is in there too, but I will try it again tomorrow (about to sleep). I'm fairly confident that the config is in the right place tho.
Thank you for your quick replies, appreciate it!!

**Comment by Javinyx** [comment]
Regarding the instructions, they were pretty clear, it's just me that didn't understand them at first haha, although if I do find a way to improve them from a newbie's perspective I'll tell you ^^.

**Comment by Javinyx** [comment]
Hey!
So I tried everything again, this is what my folder looks like, the icon is 64x64 and png. https://i.imgur.com/IV5Vxw8.png
In game this is what I get https://i.imgur.com/3CvIAuZ.png
I don't understand why the name is like that, and the icon invisible :(

Sorry for bugging you, I really like your mod :3

**Comment by thebrightspark** [comment]
Can you also show me the contents of your JSON file please?

**Comment by thebrightspark** [comment]
Oh and your icon image is wrong... please refer to my mod page on how that should be.
I have an icon template file there as well.

**Comment by Javinyx** [comment]
I have finally understood how the icon works.. just not what to name it haha, the JSON is the one above, but this is a screenshot either way: https://i.imgur.com/EaQwwzg.png

**Comment by thebrightspark** [comment]
Hmm strange everything (other than the icon) seems fine.
Can you send your logs? Post using Pastebin or similar please.

**Comment by Javinyx** [comment]
Sure, which one do you need? fml-junk or latest?

**Comment by thebrightspark** [comment]
Uhhhh I believe it's the latest? Should have all the normal console output logs in it.

**Comment by Javinyx** [comment]
Alrighty, here it goes: https://pastebin.com/BwthMp11

**Comment by thebrightspark** [comment]
Well all I see is this from my logging:
`[09:33:53] [main/INFO] [extraskills]: Read 1 extra skills from JSON file`
And there's no errors, which suggests it all worked fine...

I'm not sure what to suggest other than to try something that I know works for sure.
Try replace the contents of your skills.json with this:
`[
  {
    "name": "example",
    "localName": "Example",
    "background": "stone"
  },
  {
    "name": "test",
    "localName": "Test Skill",
    "background": "end_stone"
  }
]`
And then also drop the template icon file into the config directory too:
https://imgur.com/i8kxOoy

It should look like this:
![image](https://user-images.githubusercontent.com/11932411/38889554-fb58bdbe-4276-11e8-8958-a02e4a743496.png)

Let me know if that works for you.

**Comment by Javinyx** [comment]
Heya, bad news..
This is what I'm getting: https://i.imgur.com/vdKz803.png
With this folder: https://i.imgur.com/OFTcgTT.png
And this config: https://i.imgur.com/sAgpPqI.png
I tried leaving the icon file name the same as when downloaded but same thing happened.

**Comment by thebrightspark** [comment]
Ah yeah the name of the icon file will need to be "test.png"
Sorry about that 🙃 Let me know if changing the name works for the icon.

Although the localisation of the name should work.
I've actually been shown a better way of the doing the localisation... let me quickly try change it and we'll see if that helps.

**Comment by Javinyx** [comment]
Alrighty, I'll start by changing the name of the png haha, don't worry! :)
Let me know when to update :P

**Comment by thebrightspark** [comment]
Well I'll see if the icon works first before getting an update out 😃

**Comment by Javinyx** [comment]
Icon is working!!

**Comment by Javinyx** [comment]
Don't be sorry! You have been so kind and patient with me ^^
Let's cross our fingers hehe

**Comment by thebrightspark** [comment]
Alright, got a new version processing as we speak which should fix the translation issue.
I'm going to close this issue now, but any more issues, please do raise a new ticket 😄
