### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by TheVoidLord** [thebrightspark/ExtraSkills#5]
I'm not sure exactly what I'm doing wrong here, I tried without having [ ] around each skill and only one of them worked. but the current config none of the skills work. If you need any more information please let me know as I'm very confused currently.

[
  {
    "name": "example",
    "localName": "Example",
    "background": "stone",
  }
]
[
  {
	"name": "swordskills",
    "localName": "Sword Skills",
    "background": "stone"
  }
]
[
  {
	"name": "power",
    "localName": "Power",
    "background": "stone",
  }
]
[	
  {
    "name": "processing",
	"localName": "Processing",
    "background": "stone",
  }
]
[
  {
	"name": "tinkering",
	"localName": "Tinkering",
	"background": "stone",
  }
]

**Comment by TheVoidLord** [comment]
Never mind, a friend of mine showed me where I went wrong. Sorry about bothering you. Thank you for the great mod though.

**Comment by Dynamiczbee** [comment]
Bruh at least post the working one, some of us don't have friends who can help lmao.

**Comment by TheVoidLord** [comment]
Dude, you are so lucky I'm bad at deleting things. I haven't worked on this in months and have abandoned it, I just luckily had a backup.

I did eventually get this to work, but you have to have image files for it to call on before it will work. (For testing purposes I just copied the test image and pasted it with the skill names.

I hope this helps, as it's honestly all I remember from this project/issue.

[
  {
    "name": "example",
    "localName": "Example",
    "background": "stone"
  },
  {
    "name": "swordskills",
    "localName": "Sword Skills",
    "background": "stone"
  },
  {
    "name": "power",
    "localName": "Power",
    "background": "stone"
  },
  {
    "name": "processing",
    "localName": "Processing",
    "background": "stone"
  },
  {
    "name": "tinkering",
    "localName": "Tinkering",
    "background": "stone"
  }
]
