### ISSUE TITLE
Question - Where does player data get saved for this mod?

### ISSUE THREAD

**Issue by tyon2006** [thebrightspark/ExtraSkills#6]
Hello! This isn't an issue so much as a question. I am working with a plugin that syncs player data between servers. I got every aspect of it working on my pack except for skill/trait data. Can you help me understand where this data is saved so I can attempt to go read it and sync it?

**Comment by thebrightspark** [comment]
This mod doesn't store anything - it just registers your custom skills with Reskillable. I suggest you take up that question with the developers of that mod instead.
