### ISSUE TITLE
How do I save the PNG images?

### ISSUE THREAD

**Issue by Divine144** [thebrightspark/ExtraSkills#7]
How do I make the final image? I have four 64x64 PNG images but I dont know how to combine them nor put them in the top row of 64x16. Please help me.

**Comment by thebrightspark** [comment]
As explained in the mod description, you need 4 16x16 images put into a single 64x64 image. A template of which I provide here: https://imgur.com/i8kxOoy
You can use any image editor to do this.

**Comment by Divine144** [comment]
Ok. Thank you for the clarification. I think I can figure it out now.
