### ISSUE TITLE
Could you add better documentation? (and a way to add traits to skills so this is somewhat useful?)

### ISSUE THREAD

**Issue by vizthex123** [thebrightspark/ExtraSkills#8]
Title. I don't know what variables the .json can use, and  don't want to dig through the source code ot find it.

Do you mind making a wiki here (and linking it on the CurseForge page)?

Or maybe tell the project followers they can make pages and you can just port them here?

Love the concept, but I need to know how to use it.

**Comment by thebrightspark** [comment]
Not sure what you mean by `variables`, but everything is described in the mod description on CurseForge.

**Comment by vizthex123** [comment]
Yeah I was thinking  you could make the traits do things (like edit vanilla attributes), but it appears you can't.

**Comment by thebrightspark** [comment]
No you can't add traits in this mod.
I remember considering it early on, but I can't remember why I didn't add the ability to do that. It was either I couldn't think of a good way to go about it, or I literally just couldn't as Reskillable didn't allow for it.

**Comment by vizthex123** [comment]
Ah man, that's unfortunate. Ah well.
